### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by kurtinlane** [troylelandshields/omgrpc#1]
Allow edit of connection... so I can easily change between dev, prod and local when I'm testing

**Comment by troylelandshields** [comment]
How about you add it yourself instead of just complaining to me?

:D

jkjkjkjkjk

**Comment by kurtinlane** [comment]
Hahahahah I don't have access already tried. Clearly this is a one man show

**Comment by jnewmano** [comment]
+1

**Comment by troylelandshields** [comment]
Fix'd

**Comment by troylelandshields** [comment]
It will be in the next release
