### ISSUE TITLE
Cannot run omgrpc on mac os.

### ISSUE THREAD

**Issue by thefishermanhacker** [troylelandshields/omgrpc#15]
Hi,
I followed your steps and i'm getting the following erros.

`Error: The module '/Users/slevi/tools/omgrpc/node_modules/grpc/src/node/extension_binary/grpc_node.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:640:18)
    at Module.load (module.js:512:32)
    at tryModuleLoad (module.js:471:12)
    at Function.Module._load (module.js:463:3)
    at Module.require (module.js:522:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/slevi/tools/omgrpc/node_modules/grpc/src/node/src/grpc_extension.js:45:15)
    at Module._compile (module.js:595:32)
    at Object.Module._extensions..js (module.js:610:10)
    at Module.load (module.js:512:32)
`

Check attachment. 
![screen shot 2017-07-02 at 11 35 16 am](https://user-images.githubusercontent.com/3106554/27768383-ff8c4bac-5f1a-11e7-9cf0-56968b617502.png)

**Comment by troylelandshields** [comment]
hmm, and this is trying to run from source right (not the packaged app that can be downloaded from the Release tab)?

**Comment by thefishermanhacker** [comment]
Yes from the source.

**Comment by thefishermanhacker** [comment]
release works fine.

**Comment by troylelandshields** [comment]
Sorry for the slow response. Can you try running `npm install -g node-pre-gyp`
`npm install -g nw-gyp` and then trying to build it again?

**Comment by kurtinlane** [comment]
I had issues running it a few months ago. The readme was updated so I pulled the latest and followed the readme and it worked!

**Comment by troylelandshields** [comment]
I'm going to close this as it seems out-of-date by now, let me know if you're still trying to run it and still having issues.
