### ISSUE TITLE
trying to open a proto file 

### ISSUE THREAD

**Issue by kurtinlane** [troylelandshields/omgrpc#2]
![screen shot 2016-12-22 at 1 18 58 pm](https://cloud.githubusercontent.com/assets/5891949/21439086/42bc42ba-c849-11e6-8002-adbdfc39cd44.png)

**Comment by kurtinlane** [comment]
![screen shot 2016-12-22 at 1 19 59 pm](https://cloud.githubusercontent.com/assets/5891949/21439107/5dcddba4-c849-11e6-87ca-e40934475f2a.png)

**Comment by troylelandshields** [comment]
The issue is the way you are importing. All of your imports need to have a common parent directory or else you can't import.

For the ptypes, use the `https://github.com/golang/protobuf/tree/master/ptypes` ptypes for imports instead.
