### ISSUE TITLE
v2.0.0 missing download

### ISSUE THREAD

**Issue by joshadambell** [troylelandshields/omgrpc#21]

**Comment by kurtinlane** [comment]
there is a bug... i didn't close it either time

**Comment by joshadambell** [comment]
This @kurtinlane guy is a joke. Someone needs to revoke his rights!

**Comment by troylelandshields** [comment]
I think I have the fix! I'll upload the app ASAP

**Comment by troylelandshields** [comment]
It's uploaded now: https://github.com/troylelandshields/omgrpc/releases/tag/v0.2.0

Will you let me know if you have issues?

You guys use kubernetes over there right @joshadambell ? @jnewmano added a new dope-ass feature for hitting kubernetes services that uses `kubectl` to open a proxy.
