### ISSUE TITLE
Not Sending Requests

### ISSUE THREAD

**Issue by cnaimoli** [troylelandshields/omgrpc#35]
I followed all the directions.  I get the UI.  I drag and drop my file into the UI.  Everything is shown.  I connect to the IP address.  But when I hit "Send", nothing happens.  

I'm working on macOS High Sierra 10.13.2

**Comment by Crevil** [comment]
To be able to give some directed guidance, could you add some more context?
Where is your server running? Locally or do you use the Kubernetes feature?
What kind of server are you running? Node.js, Go, Ruby, etc.?
Can your server indicate that a handler is hit? Maybe your request hits the server but a response is not written and because of this the request is not resolved.

**Comment by troylelandshields** [comment]
Are there any errors in the javascript console? My bet is that your JSON input isn't valid JSON. Unfortunately, right now that doesn't give you a friendly error, it just appears to do nothing. Here's an issue about that: https://github.com/troylelandshields/omgrpc/issues/34

**Comment by krishan507** [comment]
I am also having a similar issue. I am on macOS High Sierra 10.13.3. I am running a Go server locally. Specifically this example https://grpc.io/docs/quickstart/go.html#update-the-server

If you need any more information please let me know

The error in the console is shown below
<img width="720" alt="screen shot 2018-03-08 at 9 25 00 pm" src="https://user-images.githubusercontent.com/17839816/37188989-a06463e6-2317-11e8-860e-b5b01b4825c4.png">

**Comment by cnaimoli** [comment]
Sorry for delayed response:

Our grpc server runs in AWS ECS container for now, Our vision is to run all our grpc service containers in kubernetes cluster running in AWS or inhouse infrastructure.
we use java server.
“Maybe your request hits the server but a response is not written and because of this the request is not resolved” -> we need to debug

**Comment by krishan507** [comment]
My issue was resolved by changing the version of the node grpc dependency from ```"grpc": "^1.6.0"``` to ```"grpc": "1.8.4"``` in ```package.json```. It looks like the updated grpc dependency ( >1.8.4) breaks omgprc

**Comment by troylelandshields** [comment]
Just changed that in the package.json, so it should build now. Thanks for finding it!
