### ISSUE TITLE
Need instructions on setting project up for development

### ISSUE THREAD

**Issue by joshadambell** [troylelandshields/omgrpc#9]

**Comment by troylelandshields** [comment]
Ok, I'll work on this. Did you download the latest version? It's got a couple nice improvements.

**Comment by joshadambell** [comment]
Yes I did. I created an issue as it's broken with json. The form is a great idea.

**Comment by troylelandshields** [comment]
hey josh, if you get a few min I'd love it if you tried following the steps I added to the readme to see if you can get it running locally.

**Comment by joshadambell** [comment]
I finally got time to set this up today. I'll let you know how it goes.

**Comment by joshadambell** [comment]
👍
